# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67a3828b270b911f1df8c270fa1950b73074bea7b616d58ebb079a2b4fe0e395d5f48de361fef2229bf469c09c0ea5199427f5d93edbda719d30ca54eaf7bb53

test:
  secret_key_base: a741a07a76314da74fb59264fa905fe50e14600a5e510198c78c20c6a6aac29cfba8d40d58252b6547b0e4ddd54cce7830b620bb2f0aaa97f596093b2e01e667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
